### PR TITLE
disable sampler classifiers

### LINKED ISSUE #474: investigate using preconditions to inform negative data creation in sampler learning

### PR DESCRIPTION
**Pull request by ronuchit**
Edit: opening this PR to turn off sampler classifiers, because they seem unnecessary based on experimentation. Can revert if it's causing problems later down the line.

some of the commits in this PR also close #474 (in particular, the experiment with `--sampler_classifier_neg_check_pre True`)

2/16/22 overnight experiments:

140 jobs per supercloud
ronuchit: control
tslvr: filter out neg data that doesn't match preconditions (`--sampler_classifier_neg_check_pre True`)
njk: no sampler classifier at all (`--sampler_disable_classifier True`)

cc @tomsilver @NishanthJKumar

### CODE REVIEW

**Comment by ronuchit** [comment]
morning update: monthly maintenance began overnight, will retry this experiment tonight. but initial evidence from the njk run suggests that sampler classifiers aren't needed at all

**Comment by ronuchit** [comment]
results:
ronuchit: control
```
NUM_TRAIN_TASKS     NUM_SOLVED  AVG_NUM_PREDS AVG_TEST_TIME  AVG_NODES_CREATED       LEARNING_TIME  NUM_SEEDS
EXPERIMENT_ID                                                                                                                                       
blocks_invent_allexclude_50               50.00 (0.00)   49.60 (0.80)    6.20 (0.60)   0.35 (0.09)  2887.07 (1494.20)    1041.16 (134.08)         10
blocks_invent_noexclude_50                50.00 (0.00)   49.50 (0.81)    5.30 (0.64)   0.28 (0.08)  2906.13 (1508.54)     300.99 (122.37)         10
blocks_noinvent_allexclude_50             50.00 (0.00)    1.60 (1.20)    2.00 (0.00)   3.37 (2.57)    409.67 (100.78)      435.99 (24.54)         10
blocks_noinvent_noexclude_50              50.00 (0.00)   49.70 (0.64)    5.00 (0.00)   0.29 (0.08)  2884.88 (1496.87)        80.06 (6.74)         10
blocks_oracle                             50.00 (0.00)   50.00 (0.00)    5.00 (0.00)   0.21 (0.07)  2909.11 (1536.50)         0.00 (0.00)         10
cover_invent_allexclude_50                50.00 (0.00)   50.00 (0.00)    5.90 (0.54)   0.01 (0.00)        4.97 (0.36)      146.54 (18.13)         10
cover_invent_noexclude_50                 50.00 (0.00)   50.00 (0.00)    7.00 (0.45)   0.01 (0.00)        4.97 (0.36)       98.85 (14.61)         10
cover_noinvent_allexclude_50              50.00 (0.00)   12.60 (2.54)    1.00 (0.00)   0.06 (0.13)        5.00 (0.00)      242.16 (25.73)         10
cover_noinvent_noexclude_50               50.00 (0.00)   50.00 (0.00)    5.00 (0.00)   0.14 (0.05)        6.83 (0.32)        41.45 (5.04)         10
cover_oracle                              50.00 (0.00)   50.00 (0.00)    5.00 (0.00)   0.05 (0.01)        6.83 (0.32)         0.00 (0.00)         10
painting_invent_allexclude_50             50.00 (0.00)   45.50 (3.69)   23.20 (2.68)   0.27 (0.10)    356.82 (111.40)  19117.35 (3159.39)         10
painting_invent_noexclude_50              50.00 (0.00)   45.60 (3.72)   21.60 (2.42)   0.23 (0.05)    362.60 (110.45)   6568.98 (1339.65)         10
painting_noinvent_allexclude_50           50.00 (0.00)    0.00 (0.00)      nan (nan)     nan (nan)          nan (nan)      333.19 (26.58)         10
painting_noinvent_noexclude_50            50.00 (0.00)   48.20 (1.33)   13.00 (0.00)   0.48 (0.11)   1960.08 (635.62)      202.09 (16.95)         10
painting_oracle                           50.00 (0.00)   50.00 (0.00)   13.00 (0.00)   0.41 (0.07)   2812.65 (877.62)         0.00 (0.00)         10
repeated_nextto_noinvent_allexclude_50    50.00 (0.00)   10.60 (1.69)    1.00 (0.00)   0.13 (0.02)     323.85 (19.77)        19.45 (1.15)         10
repeated_nextto_noinvent_noexclude_50     50.00 (0.00)   48.60 (1.56)    3.00 (0.00)   0.46 (0.26)       49.05 (1.19)      101.85 (77.20)         10
repeated_nextto_oracle                    50.00 (0.00)   50.00 (0.00)    3.00 (0.00)   0.01 (0.00)       47.37 (0.72)         0.00 (0.00)         10
tools_invent_allexclude_50                50.00 (0.00)  25.40 (11.80)  44.00 (13.45)   0.33 (0.27)    470.56 (567.48)   7782.16 (3614.36)         10
tools_invent_noexclude_50                 50.00 (0.00)  30.30 (12.33)  37.00 (10.88)   0.26 (0.15)    457.14 (355.56)   3335.42 (1873.93)         10
tools_noinvent_allexclude_50              50.00 (0.00)    0.00 (0.00)      nan (nan)     nan (nan)          nan (nan)       559.26 (8.06)         10
tools_noinvent_noexclude_50               50.00 (0.00)   49.30 (0.78)   15.00 (0.00)   0.60 (0.14)   3892.67 (962.56)      130.77 (15.26)         10
tools_oracle                              50.00 (0.00)   50.00 (0.00)   15.00 (0.00)   0.46 (0.10)  4151.60 (1052.72)         0.00 (0.00)         10
```

tslvr: filter out neg data that doesn't match preconditions (--sampler_classifier_neg_check_pre True)
```
NUM_TRAIN_TASKS     NUM_SOLVED  AVG_NUM_PREDS AVG_TEST_TIME  AVG_NODES_CREATED       LEARNING_TIME  NUM_SEEDS
EXPERIMENT_ID                                                                                                                                       
blocks_invent_allexclude_50               50.00 (0.00)   49.60 (0.80)    6.20 (0.60)   0.46 (0.09)  2887.07 (1494.20)    1025.98 (139.43)         10
blocks_invent_noexclude_50                50.00 (0.00)   49.50 (0.81)    5.30 (0.64)   0.42 (0.09)  2906.13 (1508.54)     300.90 (130.15)         10
blocks_noinvent_allexclude_50             50.00 (0.00)    1.50 (1.20)    2.00 (0.00)   2.93 (2.44)     382.79 (91.77)      434.78 (23.82)         10
blocks_noinvent_noexclude_50              50.00 (0.00)   49.70 (0.64)    5.00 (0.00)   0.40 (0.08)  2884.88 (1496.87)        80.53 (6.69)         10
blocks_oracle                             50.00 (0.00)   50.00 (0.00)    5.00 (0.00)   0.22 (0.08)  2909.11 (1536.50)         0.00 (0.00)         10
cover_invent_allexclude_50                50.00 (0.00)   50.00 (0.00)    5.90 (0.54)   0.01 (0.00)        4.97 (0.36)      158.43 (26.37)         10
cover_invent_noexclude_50                 50.00 (0.00)   50.00 (0.00)    7.00 (0.45)   0.01 (0.00)        4.97 (0.36)      100.37 (16.03)         10
cover_noinvent_allexclude_50              50.00 (0.00)   12.60 (2.54)    1.00 (0.00)   0.14 (0.41)        5.00 (0.00)      253.00 (30.80)         10
cover_noinvent_noexclude_50               50.00 (0.00)   50.00 (0.00)    5.00 (0.00)   0.14 (0.05)        6.83 (0.32)        42.27 (5.60)         10
cover_oracle                              50.00 (0.00)   50.00 (0.00)    5.00 (0.00)   0.07 (0.05)        6.83 (0.32)         0.00 (0.00)         10
painting_invent_allexclude_50             50.00 (0.00)   45.70 (3.87)   23.20 (2.68)   0.29 (0.10)    363.87 (115.82)  19243.00 (3236.04)         10
painting_invent_noexclude_50              50.00 (0.00)   45.60 (3.72)   21.60 (2.42)   0.25 (0.06)    362.89 (110.24)   6464.79 (1061.94)         10
painting_noinvent_allexclude_50           50.00 (0.00)    0.00 (0.00)      nan (nan)     nan (nan)          nan (nan)      320.67 (17.84)         10
painting_noinvent_noexclude_50            50.00 (0.00)   48.10 (1.51)   13.00 (0.00)   0.51 (0.10)   1963.33 (635.75)      159.00 (16.95)         10
painting_oracle                           50.00 (0.00)   50.00 (0.00)   13.00 (0.00)   0.40 (0.06)   2812.65 (877.62)         0.00 (0.00)         10
repeated_nextto_noinvent_allexclude_50    50.00 (0.00)   10.60 (1.69)    1.00 (0.00)   0.12 (0.02)     323.85 (19.77)        19.86 (3.91)         10
repeated_nextto_noinvent_noexclude_50     50.00 (0.00)   48.70 (1.19)    3.00 (0.00)   0.49 (0.27)       49.21 (1.40)       98.83 (76.16)         10
repeated_nextto_oracle                    50.00 (0.00)   50.00 (0.00)    3.00 (0.00)   0.01 (0.00)       47.37 (0.72)         0.00 (0.00)         10
tools_invent_allexclude_50                50.00 (0.00)  25.00 (11.43)  41.30 (10.52)   0.41 (0.34)    469.46 (542.51)   7089.67 (2178.88)         10
tools_invent_noexclude_50                 50.00 (0.00)  28.50 (13.03)  38.00 (10.92)   0.29 (0.25)    442.02 (367.77)   3384.89 (1769.49)         10
tools_noinvent_allexclude_50              50.00 (0.00)    0.00 (0.00)      nan (nan)     nan (nan)          nan (nan)       562.13 (6.89)         10
tools_noinvent_noexclude_50               50.00 (0.00)   49.00 (1.10)   15.00 (0.00)   0.56 (0.09)  3700.59 (1161.45)      110.37 (11.35)         10
tools_oracle                              50.00 (0.00)   50.00 (0.00)   15.00 (0.00)   0.45 (0.08)  4151.60 (1052.72)         0.00 (0.00)         10
```

njk: no sampler classifier at all (--sampler_disable_classifier True)
```
NUM_TRAIN_TASKS     NUM_SOLVED  AVG_NUM_PREDS AVG_TEST_TIME  AVG_NODES_CREATED       LEARNING_TIME  NUM_SEEDS
EXPERIMENT_ID                                                                                                                                       
blocks_invent_allexclude_50               50.00 (0.00)   49.60 (0.80)    6.20 (0.60)   0.29 (0.08)  2887.07 (1494.20)    1003.67 (133.79)         10
blocks_invent_noexclude_50                50.00 (0.00)   49.50 (0.81)    5.30 (0.64)   0.24 (0.07)  2906.13 (1508.54)     268.46 (135.84)         10
blocks_noinvent_allexclude_50             50.00 (0.00)    1.80 (1.17)    2.00 (0.00)   1.50 (1.90)     426.69 (94.45)      188.40 (46.44)         10
blocks_noinvent_noexclude_50              50.00 (0.00)   49.70 (0.64)    5.00 (0.00)   0.23 (0.07)  2884.88 (1496.87)       50.45 (10.01)         10
blocks_oracle                             50.00 (0.00)   50.00 (0.00)    5.00 (0.00)   0.21 (0.07)  2909.11 (1536.50)         0.00 (0.00)         10
cover_invent_allexclude_50                50.00 (0.00)   50.00 (0.00)    5.90 (0.54)   0.00 (0.00)        4.97 (0.36)      127.13 (16.42)         10
cover_invent_noexclude_50                 50.00 (0.00)   50.00 (0.00)    7.00 (0.45)   0.00 (0.00)        4.97 (0.36)       78.31 (11.55)         10
cover_noinvent_allexclude_50              50.00 (0.00)   12.60 (2.54)    1.00 (0.00)   0.00 (0.00)        5.00 (0.00)        29.80 (4.07)         10
cover_noinvent_noexclude_50               50.00 (0.00)   50.00 (0.00)    5.00 (0.00)   0.11 (0.04)        6.83 (0.32)        22.71 (3.54)         10
cover_oracle                              50.00 (0.00)   50.00 (0.00)    5.00 (0.00)   0.05 (0.01)        6.83 (0.32)         0.00 (0.00)         10
painting_invent_allexclude_50             50.00 (0.00)   46.00 (3.71)   23.20 (2.68)   0.20 (0.04)    370.00 (120.70)  19149.14 (3318.65)         10
painting_invent_noexclude_50              50.00 (0.00)   45.80 (3.49)   21.60 (2.42)   0.17 (0.03)    364.14 (109.66)   6448.34 (1383.71)         10
painting_noinvent_allexclude_50           50.00 (0.00)    0.00 (0.00)      nan (nan)     nan (nan)          nan (nan)       87.71 (21.62)         10
painting_noinvent_noexclude_50            50.00 (0.00)   49.00 (1.10)   13.00 (0.00)   0.44 (0.08)   2112.33 (624.98)      107.22 (14.46)         10
painting_oracle                           50.00 (0.00)   50.00 (0.00)   13.00 (0.00)   0.42 (0.07)   2812.65 (877.62)         0.00 (0.00)         10
repeated_nextto_noinvent_allexclude_50    50.00 (0.00)   10.60 (1.69)    1.00 (0.00)   0.18 (0.18)     323.85 (19.77)        19.81 (3.78)         10
repeated_nextto_noinvent_noexclude_50     50.00 (0.00)   49.40 (0.80)    3.00 (0.00)   0.55 (0.32)       50.13 (1.06)       81.26 (81.32)         10
repeated_nextto_oracle                    50.00 (0.00)   50.00 (0.00)    3.00 (0.00)   0.01 (0.00)       47.37 (0.72)         0.00 (0.00)         10
tools_invent_allexclude_50                50.00 (0.00)  24.70 (11.31)  41.20 (12.25)   0.34 (0.33)    566.60 (617.34)   7078.63 (3035.50)         10
tools_invent_noexclude_50                 50.00 (0.00)  28.40 (12.84)  38.10 (10.88)   0.23 (0.21)    456.46 (385.01)   3286.40 (1739.76)         10
tools_noinvent_allexclude_50              50.00 (0.00)    0.00 (0.00)      nan (nan)     nan (nan)          nan (nan)      331.68 (73.48)         10
tools_noinvent_noexclude_50               50.00 (0.00)   49.50 (0.67)   15.00 (0.00)   0.53 (0.09)  3982.56 (1028.07)        76.52 (8.02)         10
tools_oracle                              50.00 (0.00)   50.00 (0.00)   15.00 (0.00)   0.44 (0.08)  4151.60 (1052.72)         0.00 (0.00)         10
```

**Comment by ronuchit** [comment]
@tomsilver results above seem to suggest that samplers aren't doing much of anything for us. so of course, whether you include the precondition check in negative data generation doesn't matter either

**Review by tomsilver — APPROVED** [review]
lgtm. @czeng6 take note, this will affect your open PR

**Pull request merged**
