### PR TITLE
renames "side predicates" to "ignore effects"

### PR DESCRIPTION
**Pull request by NishanthJKumar**
Given we're using "ignore effects" in the paper, I figure the code should match this terminology so that no one gets confused in the future.

### CODE REVIEW

**Comment by tomsilver** [comment]
good idea! did you do this manually or in an automated way?

**Comment by NishanthJKumar** [comment]
automated, with find and replace!

**Comment by ronuchit** [comment]
there are still a couple cases:
```
(igibson) rohan@Rohans-MacBook-Pro:~/Documents/predicators$ git grep -i "side pre"
src/ground_truth_nsrts.py:    # Note that NextTo isn't a side predicate here because it's not
src/nsrt_learning/strips_learning/clustering_learner.py:            # ...consider changing each of its add effects to a side predicate.
src/nsrt_learning/strips_learning/clustering_learner.py:    function for side predicate learning."""
src/nsrt_learning/strips_learning/clustering_learner.py:    function for side predicate learning."""
src/structs.py:        (either add or delete) into a side predicate."""
src/utils.py:    # application of the operator, because if the side predicate
(igibson) rohan@Rohans-MacBook-Pro:~/Documents/predicators$ git grep -i "side_pre"
src/nsrt_learning/strips_learning/clustering_learner.py:                        pnad.op.effect_to_side_predicate(
src/structs.py:    def effect_to_side_predicate(self, effect: LiftedAtom,
tests/test_structs.py:        strips_operator.effect_to_side_predicate(next(
tests/test_structs.py:        strips_operator.effect_to_side_predicate(next(
tests/test_structs.py:        strips_operator.effect_to_side_predicate(next(iter(delete_effects)),
tests/test_structs.py:    sidelined_add = strips_operator.effect_to_side_predicate(
tests/test_structs.py:    sidelined_delete = strips_operator.effect_to_side_predicate(
(igibson) rohan@Rohans-MacBook-Pro:~/Documents/predicators$ git grep -i "side-pre"
(igibson) rohan@Rohans-MacBook-Pro:~/Documents/predicators$ git grep -i "sidepre"
```

**Comment by NishanthJKumar** [comment]
okay sorry about that; looks like i didn't catch them all before. Should be good now!

**Review by tomsilver — APPROVED** [review]
one more thing to sanity check is the names of files

**Comment by NishanthJKumar** [comment]
good suggestion: looks like the only file we actually use this name for is `run_predicators_sidelining_experiments.sh`. Should we rename to `run_predicators_ignore_effects_experiments.sh`?

**Comment by tomsilver** [comment]
yeah or just `run_ignore_effects_experiments.sh`

**Pull request merged**
