### PR TITLE
fix to doors action space

### PR DESCRIPTION
**Pull request by tomsilver**
fixes a crash with oracle options. the old action bounds didn't make sense, they were left over from a time where I was thinking about door handle rotations literally...

### CODE REVIEW

**Review by ronuchit — APPROVED** [review]
will this affect the other methods?

**Comment by tomsilver** [comment]
yeah it might lead to improvements for the other methods too? we'll see

**Comment by tomsilver** [comment]
partial supercloud results
doors_num_train_tasks_perc_solved

**Comment by tomsilver** [comment]
partial supercloud results
doors_num_train_tasks_perc_solved

**Pull request merged**
