### PR TITLE
speed up oracle testing

### PR DESCRIPTION
**Pull request by ronuchit**
@tomsilver i wanted to do this but cover_regrasp is failing to plan. related to #417 perhaps?

### CODE REVIEW

**Review by tomsilver — APPROVED** [review]
That's weird. I'll take a look later.

**Comment by tomsilver** [comment]
@ronuchit fyi after rebasing off the fixes to cover_regrasp, it looks like the remaining issue is related to cluttered table

**Comment by tomsilver** [comment]
@ronuchit my PR with the new analysis script (#416) is failing due to timeouts in unrelated tests, is there any chance that this PR caused that?

**Comment by ronuchit** [comment]
i don't think so, i'd say look into what's causing test_datasets.py to fail... this PR shouldn't affect that

**Pull request merged**
