### PR TITLE
script for converting saved eval traj to lisdf plan 

### PR DESCRIPTION
**Pull request by tomsilver**
closes #1202 (to avoid merge conflicts)

### CODE REVIEW

**Comment by tomsilver** [comment]
@williamshen-nz it looks like the py.typed thing isn't working for lisdf, but I'm not sure why -- do you have any immediate ideas?

**Comment by williamshen-nz** [comment]
hmm there is no `py.typed` when I pip install lisdf, I'll have a look at what's happening

```zsh
❯ pwd
/tmp/env/lib/python3.9/site-packages/lisdf
❯ ls
__init__.py    __pycache__    components     parsing        plan_executor  planner_output utils
```

**Comment by williamshen-nz** [comment]
I spent some time trying to fix things but using the MANIFEST.in so the py.typed actually pops up in the site-packages.

For some reason mypy still doesn't like it. Will leave it for now

**Comment by tomsilver** [comment]
@williamshen-nz thanks a lot for investigating. I think I found something that seems to work? See https://github.com/Learning-and-Intelligent-Systems/lisdf/pull/27

**Review by williamshen-nz — APPROVED** [review]
:shipit:

**Pull request merged**
