### PR TITLE
Fix pnad search backchaining

### PR DESCRIPTION
**Pull request by ashayathalye**
`pnad_search` with predicate invention by oracle clustering enters an infinite loop in the blocks environment due to an issue with the backchaining implementation. This happens because `PNADSearchSTRIPSLearner.backchain` only tries the _single_ best matching pnad for a given segment – if that pnad doesn't satisfy the necessary atoms check, it does not check if any other pnads would work. In the specific example where this issue arises, `pnad_search` repeatedly uncovers the same segment over and over: a pnad (`STRIPS-Pick8`) covers a particular segment and has this segment in its datastore, but `PNADSearchSTRIPSLearner.backchain` continues to identify this segment as an uncovered segment. This happens because in the search for the first uncovered segment, when backchaining, it only tries the single best matching pnad `STRIPS-Pick9`, and when that pnad fails the necessary atoms check, it does not try`STRIPS-Pick8`, which would work to extend the chain further. The simple and obvious fix is to try all pnads, in order of "best matching". 

You can observe this issue by running `python predicators/main.py --env blocks --excluded_predicates all --approach grammar_search_invention --num_train_tasks 200 --seed 0 --grammar_search_max_predicates 200 --grammar_search_pred_clusterer oracle --grammar_search_pred_selection_approach clustering --strips_learner pnad_search --pnad_search_timeout 1200 --offline_data_method demo+gt_operators` on branch `master`. 

After the small change in this PR, this same command gets 48/50 in blocks. 

To make sure this doesn't break anything, I will report back with results from supercloud, on both (1) predicate invention via score optimization (from the original predicate invention paper) and (2) predicate invention via oracle clustering. 

I'm surprised this issue hasn't surfaced earlier – it seems like it could be a common occurence.

### CODE REVIEW

**Comment by ashayathalye** [comment]
Initial supercloud results using predicate invention via oracle clustering: 

```
                      NUM_TRAIN_TASKS    NUM_SOLVED AVG_NUM_PREDS AVG_TEST_TIME  AVG_NODES_CREATED   LEARNING_TIME AVG_REF_COST  NUM_SEEDS
EXPERIMENT_ID
blocks_main_200demo     200.00 (0.00)  48.70 (1.10)  14.00 (0.00)   0.67 (0.17)  3099.28 (1140.61)  161.40 (38.15)  1.10 (0.17)         10
cover_main_200demo      200.00 (0.00)  48.80 (0.75)  10.00 (0.00)   0.01 (0.00)        4.92 (0.16)    38.07 (1.13)  0.13 (0.01)          5
painting_main_200demo   200.00 (0.00)  49.90 (0.30)  50.00 (0.00)   0.52 (0.10)    855.42 (257.93)   332.22 (6.66)  1.23 (0.12)         10
tools_main_200demo      200.00 (0.00)  49.70 (0.64)  58.00 (0.00)   0.52 (0.08)    664.78 (104.78)   278.19 (5.74)  1.01 (0.09)         10
```

**Comment by ashayathalye** [comment]
Nishanth confirmed that it is not unexpected for an uncovered segment to be found in an existing pnad's datastore during pnad search, because something like "when a particular uncovered segment is discovered, and a pnad is created to cover it, all segments that use the same option as that segment will be added to the new pnad's datastore (to aid in precondition computation), and some of those added segments may later be uncovered segments". 

After removing the assertion that uncovered segments are not found in an existing pnad's datastore, using predicate invention via oracle clustering and pnad search for operator learning, we get the following results: 

```
                     NUM_TRAIN_TASKS    NUM_SOLVED AVG_NUM_PREDS AVG_TEST_TIME  AVG_NODES_CREATED   LEARNING_TIME AVG_REF_COST  NUM_SEEDS
EXPERIMENT_ID
blocks_main_200demo     200.00 (0.00)  48.70 (1.10)  14.00 (0.00)   0.67 (0.17)  3099.28 (1140.61)  161.40 (38.15)  1.10 (0.17)         10
cover_main_200demo   200.00 (0.00)  49.20 (0.75)  10.00 (0.00)   0.01 (0.00)       4.88 (0.15)  38.70 (1.86)  0.13 (0.01)         10
painting_main_200demo   200.00 (0.00)  49.90 (0.30)  50.00 (0.00)   0.52 (0.10)    855.42 (257.93)   332.22 (6.66)  1.23 (0.12)         10
tools_main_200demo      200.00 (0.00)  49.70 (0.64)  58.00 (0.00)   0.52 (0.08)    664.78 (104.78)   278.19 (5.74)  1.01 (0.09)         10
```

**Comment by ashayathalye** [comment]
(I don't think unit tests relating to any pnad search stuff are failing – I think they are other ones? )

**Comment by NishanthJKumar** [comment]
Results from running ignore effects experiments on supercloud:
```
AGGREGATED DATA OVER SEEDS:
                                                NUM_TRAIN_TASKS     NUM_SOLVED AVG_NUM_PREDS AVG_TEST_TIME    AVG_NODES_CREATED  LEARNING_TIME AVG_REF_COST  NUM_SEEDS
EXPERIMENT_ID                                                                                                                                                         
painting_pnadsearch_10demo                         10.00 (0.00)   45.50 (4.48)  15.00 (0.00)   0.44 (0.12)     2097.72 (782.53)   52.24 (1.04)  1.04 (0.09)         10
painting_pnadsearch_25demo                         25.00 (0.00)   49.30 (1.00)  15.00 (0.00)   0.39 (0.09)     2371.19 (821.09)   59.07 (2.36)  1.01 (0.07)         10
painting_pnadsearch_50demo                         50.00 (0.00)   49.40 (0.66)  15.00 (0.00)   0.43 (0.13)    2758.02 (1077.04)   68.60 (2.65)  1.03 (0.10)         10
painting_pnadsearch_5demo                           5.00 (0.00)   13.20 (9.50)  15.00 (0.00)   1.14 (0.90)    1734.20 (1645.06)   48.49 (1.00)  1.61 (0.81)         10
repeated_nextto_painting_pnadsearch_10demo         10.00 (0.00)   38.80 (8.21)  19.00 (0.00)   0.96 (0.25)    3558.20 (3155.66)   88.47 (3.72)  1.28 (0.22)         10
repeated_nextto_painting_pnadsearch_50demo         50.00 (0.00)   49.50 (0.92)  19.00 (0.00)   0.74 (0.07)     1805.45 (414.37)  136.66 (4.75)  1.11 (0.05)         10
repeated_nextto_painting_pnadsearch_5demo           5.00 (0.00)  24.10 (13.32)  19.00 (0.00)   1.00 (0.40)    3738.79 (2299.53)   83.73 (6.05)  1.33 (0.29)         10
repeated_nextto_single_option_pnadsearch_10demo    10.00 (0.00)   50.00 (0.00)   3.00 (0.00)   0.04 (0.01)         88.50 (2.35)   19.04 (1.94)  0.23 (0.01)         10
repeated_nextto_single_option_pnadsearch_25demo    25.00 (0.00)   50.00 (0.00)   3.00 (0.00)   0.03 (0.00)         88.50 (2.35)   19.03 (2.07)  0.23 (0.00)         10
repeated_nextto_single_option_pnadsearch_50demo    50.00 (0.00)   50.00 (0.00)   3.00 (0.00)   0.03 (0.00)         88.50 (2.35)   18.58 (1.33)  0.22 (0.00)         10
repeated_nextto_single_option_pnadsearch_5demo      5.00 (0.00)   49.90 (0.30)   3.00 (0.00)   0.04 (0.01)        83.84 (14.86)   24.51 (3.22)  0.23 (0.01)         10
satellites_pnadsearch_10demo                       10.00 (0.00)   23.60 (8.05)  13.00 (0.00)   1.74 (0.36)    5395.76 (3902.66)   10.21 (0.22)  2.47 (0.35)         10
satellites_pnadsearch_25demo                       25.00 (0.00)   38.40 (5.43)  13.00 (0.00)   1.35 (0.26)    5157.69 (1923.91)   12.17 (0.33)  2.10 (0.26)         10
satellites_pnadsearch_50demo                       50.00 (0.00)   47.60 (1.20)  13.00 (0.00)   1.14 (0.25)    6487.61 (3123.81)   15.16 (0.42)  1.90 (0.25)         10
satellites_pnadsearch_5demo                         5.00 (0.00)    7.40 (9.60)  13.00 (0.00)   2.04 (1.12)  10541.57 (11408.96)    9.29 (0.41)  2.76 (1.15)         10
satellites_simple_pnadsearch_10demo                10.00 (0.00)   33.30 (6.84)  13.00 (0.00)   0.90 (0.42)      392.47 (204.14)   10.14 (0.60)  1.50 (0.43)         10
satellites_simple_pnadsearch_25demo                25.00 (0.00)   40.70 (7.77)  13.00 (0.00)   0.74 (0.73)      696.18 (861.29)   17.00 (7.86)  1.33 (0.72)         10
satellites_simple_pnadsearch_50demo                50.00 (0.00)   45.88 (8.30)  13.00 (0.00)   0.41 (0.62)      573.79 (737.80)   17.60 (7.60)  1.01 (0.61)          8
satellites_simple_pnadsearch_5demo                  5.00 (0.00)    7.20 (8.17)  13.00 (0.00)   1.17 (1.90)      529.28 (341.12)    9.36 (0.51)  1.74 (1.88)         10
screws_pnadsearch_10demo                           10.00 (0.00)   50.00 (0.00)   4.00 (0.00)   0.10 (0.00)        117.32 (1.06)    0.34 (0.04)  0.29 (0.00)         10
screws_pnadsearch_25demo                           25.00 (0.00)   50.00 (0.00)   4.00 (0.00)   0.10 (0.00)        117.32 (1.06)    0.68 (0.02)  0.29 (0.00)         10
screws_pnadsearch_50demo                           50.00 (0.00)   50.00 (0.00)   4.00 (0.00)   0.10 (0.00)        117.32 (1.06)    1.42 (0.04)  0.29 (0.00)         10
screws_pnadsearch_5demo                             5.00 (0.00)   50.00 (0.00)   4.00 (0.00)   0.10 (0.00)        117.32 (1.06)    0.15 (0.01)  0.29 (0.00)         10

```

**Review by NishanthJKumar — APPROVED** [review]
LGTM! Incredible catch and great work fixing @ashayathalye

**Pull request merged**
