### PR TITLE
let oracle sampler learner work with option learning

### PR DESCRIPTION
**Pull request by tomsilver**

### CODE REVIEW

**Review by ronuchit — APPROVED** [review]
i thought i had tested this before with oracle option learner, what the heck! was it breaking?

**Comment by ronuchit** [comment]
hmm, i tested on master and it works fine? i'm misunderstanding something

**Comment by tomsilver** [comment]
@ronuchit I think it only works because the oracle option learner actually has the correct names of the options. I hit the error with learned options (not yet merged)

**Comment by ronuchit** [comment]
ok, gotcha!

**Pull request merged**
