### PR TITLE
backchaining predicate invention yaml

### PR DESCRIPTION
**Pull request by tomsilver**
@NishanthJKumar I figure we should try just predicate invention + backchaining before we also try option learning. does this look right to you?

### CODE REVIEW

**Comment by NishanthJKumar** [comment]
Yup - looks right!

**Comment by tomsilver** [comment]
thanks! running on njk

**Comment by tomsilver** [comment]
**BEFORE:**
```
Git commit hashes seen in results/:
fb3fabdd8ebd7940ee98fd9d501c0ddf6163b07e


AGGREGATED DATA OVER SEEDS:
                                  NUM_TRAIN_TASKS    NUM_SOLVED AVG_NUM_PREDS  AVG_TEST_TIME  AVG_NODES_CREATED       LEARNING_TIME  NUM_SEEDS
EXPERIMENT_ID                                                                                                                                 
cover_invent_allexclude              50.00 (0.00)  49.30 (0.90)   5.90 (0.54)    0.01 (0.00)        5.00 (0.23)      155.36 (16.49)         10
painting_invent_allexclude           50.00 (0.00)  47.20 (2.56)  22.10 (2.35)    0.17 (0.05)    298.98 (120.31)  17388.04 (3794.65)         10
pybullet_blocks_invent_allexclude    50.00 (0.00)  49.30 (0.64)   6.20 (0.75)    0.45 (0.11)  4308.26 (2101.98)    2372.76 (151.12)         10
pybullet_cover_invent_allexclude     50.00 (0.00)  47.70 (1.95)   6.00 (0.45)    0.05 (0.00)        4.94 (0.22)      259.20 (20.56)         10
tools_invent_allexclude             200.00 (0.00)  47.90 (1.58)  28.80 (4.89)    0.34 (0.18)  1652.70 (1559.39)  19446.95 (2804.94)         10
```

**AFTER:**
```
Git commit hashes seen in results/:
17f05e4a00e24653237bbe17b64bc222eb4015ba


AGGREGATED DATA OVER SEEDS:
                                               NUM_TRAIN_TASKS    NUM_SOLVED AVG_NUM_PREDS AVG_TEST_TIME  AVG_NODES_CREATED       LEARNING_TIME  NUM_SEEDS
EXPERIMENT_ID                                                                                                                                             
cover-invent_allexclude_backchaining              50.00 (0.00)  49.10 (0.94)   7.10 (2.47)   0.01 (0.02)        4.89 (0.14)     401.63 (331.57)         10
painting-invent_allexclude_backchaining           50.00 (0.00)  47.80 (3.19)  19.90 (3.17)   0.25 (0.09)    424.20 (125.16)  24833.79 (6429.95)         10
pybullet_blocks-invent_allexclude_backchaining    50.00 (0.00)  48.90 (1.04)   7.10 (1.37)   0.49 (0.51)  1509.41 (2407.36)  10653.58 (6060.91)         10
pybullet_cover-invent_allexclude_backchaining     50.00 (0.00)  46.80 (1.66)   7.40 (3.77)   0.04 (0.00)        4.96 (0.20)     550.49 (570.36)         10
tools-invent_allexclude_backchaining             200.00 (0.00)  42.50 (6.00)  26.25 (3.07)   0.63 (0.49)  1907.34 (1915.79)  53233.49 (6749.18)          8
```

(two seeds for Tools still running now)

notes:
* num solved is largely consistent, except in tools, where there is a noticeable dropoff
* learning time is a bit slower, as one would expect. not disastrously -- about 2-5x
* nodes created got better in blocks, and worse in painting and tools

@NishanthJKumar

**Comment by tomsilver** [comment]
@NishanthJKumar let's merge this I guess?

**Comment by NishanthJKumar** [comment]
Sounds good to me!

**Review by NishanthJKumar — APPROVED** [review]

**Pull request merged**
