### PR TITLE
enable running experiments on supercloud

### PR DESCRIPTION
**Pull request by ronuchit**
should help with easier parallelized testing of our main pipeline to make sure there are no regressions / check for slowdowns!

### CODE REVIEW

**Comment by ronuchit** [comment]
Results:
```
                              TEST_TASKS_SOLVED TEST_TASKS_TOTAL    TOTAL_TEST_TIME         TOTAL_TIME  NUM_SEEDS
ENV             APPROACH
blocks          nsrt_learning      49.40 (0.89)     50.00 (0.00)      26.85 (15.82)     138.17 (18.66)          5
                oracle             49.40 (0.89)     50.00 (0.00)      22.19 (12.22)      22.30 (12.22)          5
cluttered_table nsrt_learning      43.20 (2.77)     50.00 (0.00)      10.85 (23.35)      30.34 (28.13)          5
                oracle             48.80 (0.84)     50.00 (0.00)        9.76 (7.89)        9.78 (7.89)          5
cover           nsrt_learning      48.80 (1.64)     50.00 (0.00)      12.77 (16.08)     226.34 (58.45)          5
                oracle             50.00 (0.00)     50.00 (0.00)        0.26 (0.00)        0.28 (0.01)          5
painting        nsrt_learning      47.00 (4.12)     50.00 (0.00)      42.62 (40.41)     287.81 (41.55)          5
                oracle             50.00 (0.00)     50.00 (0.00)        4.82 (0.12)        4.84 (0.11)          5
repeated_nextto nsrt_learning     10.40 (15.90)     50.00 (0.00)  2011.33 (1998.24)  2369.19 (2384.78)          5
                oracle             50.00 (0.00)     50.00 (0.00)        0.55 (0.01)        0.56 (0.01)          5
```

I need to look into why the timeout isn't working properly on supercloud for some seeds.

**Comment by ronuchit** [comment]
Usage:
- Log into supercloud.
- Edit and run `./analysis/run_supercloud_experiments.sh`
- Monitor with `squeue -u <username>`
- When all jobs are done, run `python analysis/analyze_supercloud_experiments.py` (on supercloud) to print out results table.

**Comment by ronuchit** [comment]
Results:
```
(predicators) ronuchit@login-4:~/predicators$ python analysis/analyze_supercloud_experiments.py
                              TEST_TASKS_SOLVED TEST_TASKS_TOTAL  TOTAL_TEST_TIME       TOTAL_TIME  NUM_SEEDS
ENV             APPROACH
blocks          nsrt_learning      49.40 (0.89)     50.00 (0.00)    22.84 (15.16)   137.80 (18.89)          5
                oracle             49.80 (0.45)     50.00 (0.00)     17.19 (9.89)     17.30 (9.89)          5
cluttered_table nsrt_learning      42.80 (1.79)     50.00 (0.00)    12.34 (26.62)    34.96 (33.12)          5
                oracle             48.80 (0.84)     50.00 (0.00)      9.76 (7.89)      9.79 (7.88)          5
cover           nsrt_learning      48.80 (1.64)     50.00 (0.00)    13.10 (15.97)   227.37 (59.59)          5
                oracle             50.00 (0.00)     50.00 (0.00)      0.26 (0.01)      0.28 (0.01)          5
painting        nsrt_learning      47.00 (4.12)     50.00 (0.00)    42.49 (40.31)   295.38 (42.24)          5
                oracle             50.00 (0.00)     50.00 (0.00)      4.82 (0.18)      4.84 (0.18)          5
repeated_nextto nsrt_learning     17.60 (19.68)     50.00 (0.00)  396.62 (303.00)  595.55 (492.89)          5
                oracle             50.00 (0.00)     50.00 (0.00)      0.53 (0.01)      0.55 (0.01)          5
```

**Review by tomsilver — APPROVED** [review]
beauty! should we update README with the instructions you include in the PR comments?

**Comment by ronuchit** [comment]
> beauty! should we update README with the instructions you include in the PR comments? and is there anything special needed to know for first-time use on supercloud? or does installation with pip work as is?

I'll include these instructions in the README for someone who already knows how to use supercloud. First-time users will need to set up the predicators repo on their own supercloud account.

**Pull request merged**
