### PR TITLE
fix initialization in online pg3

### PR DESCRIPTION
**Pull request by tomsilver**
we were accidentally starting the search for online PG3 with the old policy, which could use outdated NSRTs

### CODE REVIEW

**Review by Abraham-Mitchell — APPROVED** [review]

**Review by ronuchit — COMMENTED** [review]
don't you instead want to reset self._current_ldl = LiftedDecisionList([]) at the start of learn_ldl?

**Comment by tomsilver** [comment]
>don't you instead want to reset self._current_ldl = LiftedDecisionList([]) at the start of learn_ldl?
I considered that, but we do have a "current LDL" still technically, so I think that this is better

**Comment by ronuchit** [comment]
why would you have a current LDL if you've just called learn_ldl()?

**Comment by tomsilver** [comment]
you have it from the last learning cycle

**Pull request merged**
