### PR TITLE
add ClassVar annotations to all class variables

### LINKED ISSUE #624: Consider using ClassVar and Final typing pattern

### PR DESCRIPTION
**Pull request by ronuchit**
closes #624

### CODE REVIEW

**Review by tomsilver — APPROVED** [review]
thank you!

**Review by williamshen-nz — APPROVED** [review]
:shipit: LGTM - thanks for changing this!

**Comment by ronuchit** [comment]
Found a couple places I had missed before and fixed them. Wrote a script to verify that there are no more missing cases. Will merge now

**Comment by tomsilver** [comment]
Well now you’re just showing off

**Pull request merged**
